openapi: "3.0.3"
info:
  title: User management
  version: "1.0"
servers:
  - url: http://localhost:8000
paths:
  /users:
    get:
      summary: Get a list of users
      parameters:
        - name: page
          in: query
          required: false
          schema:
            type: integer
            example: 1
        - name: size
          in: query
          required: false
          schema:
            type: integer
            example: 20
      responses:
        "200":
          description: List of users
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UsersList"
              example:
                - id: 1
                  name: Alice
                  email: alice@example.com
                - id: 2
                  name: Bob
                  email: bob@example.com
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
              example:
                error: "Bad types for provided query parameters"

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        email:
          type: string
      required:
        - id
        - name
        - email
    UsersList:
      type: array
      items:
        $ref: "#/components/schemas/User"
